from enum import Enum


class EventType(Enum):
    CHARACTER_INTRODUCED = "CHARACTER_INTRODUCED"
    CHARACTER_DIED = "CHARACTER_DIED"

    POWER_RANK_CHANGED = "POWER_RANK_CHANGED"

    # Skill Events
    SKILL_UNLOCKED = "SKILL_UNLOCKED"
    SKILL_UPGRADED = "SKILL_UPGRADED"
    SKILL_EVOLVED = "SKILL_EVOLVED"
    SKILL_REPLACED = "SKILL_REPLACED"
    SKILL_COMBINED = "SKILL_COMBINED"
    SKILL_LOST = "SKILL_LOST"
    SKILL_RELATION_REVEALED = "SKILL_RELATION_REVEALED"

    RELATIONSHIP_CREATED = "RELATIONSHIP_CREATED"
    RELATIONSHIP_CHANGED = "RELATIONSHIP_CHANGED"
    RELATIONSHIP_ENDED = "RELATIONSHIP_ENDED"

    FACTION_INTRODUCED = "FACTION_INTRODUCED"
    FACTION_MEMBER_JOINED = "FACTION_MEMBER_JOINED"
    FACTION_MEMBER_LEFT = "FACTION_MEMBER_LEFT"
    FACTION_LEADER_CHANGED = "FACTION_LEADER_CHANGED"

    FACTION_RELATIONSHIP_CREATED = "FACTION_RELATIONSHIP_CREATED"
    FACTION_RELATIONSHIP_CHANGED = "FACTION_RELATIONSHIP_CHANGED"
    FACTION_RELATIONSHIP_ENDED = "FACTION_RELATIONSHIP_ENDED"

    LOCATION_DISCOVERED = "LOCATION_DISCOVERED"

    CUSTOM = "CUSTOM"
