import React from 'react';
import { Card } from '../../../components/ui/Card';
import { Badge } from '../../../components/ui/Badge';
import { TemporalComparisonResponse } from '../../../api/contracts/read-models';

export interface CounterfactualComparisonProps {
  divergence: TemporalComparisonResponse;
  readerChapter: number;
}

export const CounterfactualComparison: React.FC<CounterfactualComparisonProps> = ({
  divergence,
  readerChapter,
}) => {
  const summary = divergence.summary || {};

  return (
    <Card
      data-testid="counterfactual-comparison-card"
      style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}
    >
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <div>
          <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
            <h3 style={{ margin: 0, fontSize: '1rem', fontWeight: 600, color: 'var(--tsi-text-primary)' }}>
              Canonical vs. Hypothetical WorldState Divergence
            </h3>
            <Badge variant="warning" style={{ fontSize: '0.625rem' }}>
              NOT CANON
            </Badge>
          </div>
          <span style={{ fontSize: '0.75rem', color: 'var(--tsi-text-muted)' }}>
            Comparative delta generated by WorldStateComparator between Chapter {divergence.from_chapter} and Chapter {readerChapter}.
          </span>
        </div>
      </div>

      <div
        style={{
          display: 'grid',
          gridTemplateColumns: 'repeat(auto-fit, minmax(140px, 1fr))',
          gap: '10px',
        }}
      >
        <div
          style={{
            padding: '10px 12px',
            backgroundColor: 'var(--tsi-surface-secondary)',
            borderRadius: 'var(--tsi-radius-md)',
            border: '1px solid var(--tsi-border-subtle)',
          }}
        >
          <span style={{ fontSize: '0.6875rem', color: 'var(--tsi-text-muted)', textTransform: 'uppercase' }}>
            Status Diffs
          </span>
          <div style={{ fontSize: '1.125rem', fontWeight: 700, color: 'var(--tsi-status-warning)' }}>
            {(summary.characters_removed || 0) + (summary.characters_introduced || 0) + (divergence.character_changes?.length || 0)}
          </div>
        </div>

        <div
          style={{
            padding: '10px 12px',
            backgroundColor: 'var(--tsi-surface-secondary)',
            borderRadius: 'var(--tsi-radius-md)',
            border: '1px solid var(--tsi-border-subtle)',
          }}
        >
          <span style={{ fontSize: '0.6875rem', color: 'var(--tsi-text-muted)', textTransform: 'uppercase' }}>
            Power Diffs
          </span>
          <div style={{ fontSize: '1.125rem', fontWeight: 700, color: 'var(--tsi-accent-primary)' }}>
            {summary.power_changes || divergence.power_changes?.length || 0}
          </div>
        </div>

        <div
          style={{
            padding: '10px 12px',
            backgroundColor: 'var(--tsi-surface-secondary)',
            borderRadius: 'var(--tsi-radius-md)',
            border: '1px solid var(--tsi-border-subtle)',
          }}
        >
          <span style={{ fontSize: '0.6875rem', color: 'var(--tsi-text-muted)', textTransform: 'uppercase' }}>
            Relationship Diffs
          </span>
          <div style={{ fontSize: '1.125rem', fontWeight: 700, color: 'var(--tsi-status-error)' }}>
            {summary.relationships_changed || divergence.relationship_changes?.length || 0}
          </div>
        </div>

        <div
          style={{
            padding: '10px 12px',
            backgroundColor: 'var(--tsi-surface-secondary)',
            borderRadius: 'var(--tsi-radius-md)',
            border: '1px solid var(--tsi-border-subtle)',
          }}
        >
          <span style={{ fontSize: '0.6875rem', color: 'var(--tsi-text-muted)', textTransform: 'uppercase' }}>
            Skills Unlocked
          </span>
          <div style={{ fontSize: '1.125rem', fontWeight: 700, color: 'var(--tsi-status-success)' }}>
            {summary.skills_unlocked || divergence.skill_changes?.length || 0}
          </div>
        </div>
      </div>
    </Card>
  );
};
