from enum import Enum


class FactType(str, Enum):
    CHARACTER_INTRODUCED = "CHARACTER_INTRODUCED"
    CHARACTER_DIED = "CHARACTER_DIED"

    POWER_RANK_CHANGED = "POWER_RANK_CHANGED"

    SKILL_UNLOCKED = "SKILL_UNLOCKED"
    SKILL_UPGRADED = "SKILL_UPGRADED"
    SKILL_EVOLVED = "SKILL_EVOLVED"
    SKILL_LOST = "SKILL_LOST"

    RELATIONSHIP_CREATED = "RELATIONSHIP_CREATED"
    RELATIONSHIP_CHANGED = "RELATIONSHIP_CHANGED"
    RELATIONSHIP_ENDED = "RELATIONSHIP_ENDED"

    FACTION_MEMBER_JOINED = "FACTION_MEMBER_JOINED"
    FACTION_MEMBER_LEFT = "FACTION_MEMBER_LEFT"
    FACTION_LEADER_CHANGED = "FACTION_LEADER_CHANGED"
